### ISSUE TITLE
screen all orange

### ISSUE THREAD

**Issue by Gage-Xu** [iiminov/BoatGaugesAlt#1]
Hello sir, I have also encountered the same problem. After running your code, my screen is still all orange. How do you modify it？It seems that the statement still didn't work.TFT_eSprite img = TFT_eSprite(&tft)

**Comment by iiminov** [comment]
> my screen is still orange

Is a very poor description of the issue.

I am no expert in `TFT_eSPI` library but `TFT_eSprite img = TFT_eSprite(&tft);` only reserves a memory address which is used to compose the sprite which later is printed to the screen.

The fact that you're stuck on the orange screen from the ``setup()`` tells me something doesn't initialise properly. I had a similar issue with the original code on my ESP32 from AliExpress which boiled down to these lines:

```C
while(a != 44) {
  x[i] = r * cos(rad * a) + sx;
  y[i] = r * sin(rad * a) + sy;
  x2[i] = (r - 20) * cos(rad * a) + sx;
  y2[i] = (r - 20) * sin(rad * a) + sy;
  i++;
  a++;

  if(a == 360) {
    a=0;
  }
}
```

This uses a lot of memory (360 * 4 * 4 bytes per float). I assumed the code was overflowing memory that is available. Hence why I rewrote the code.

I would suggest trying to implement the [Animated Dial](https://github.com/Bodmer/TFT_eSPI/blob/master/examples/Sprite/Animated_dial/Animated_dial.ino) example from [Bodmer/TFT_eSPI](https://github.com/Bodmer/TFT_eSPI) first to confirm your setup is working.
